### ISSUE TITLE
Error in file QR_CODE.php

### ISSUE THREAD

**Issue by Daniele1985** [giauphan/qr-code#2]
There is a problem in file QR_CODE.php under the folder qr-code.

At line 234, the method svg has bad declaration: there is a "," that you need to remove

Actual code : 

`public static function svg (string $text, $outfile = false, $level = QR_ECLEVEL_L, int $size = 3, int $margin = 4, bool $saveAndPrint = false, int $back_color = QR_WHITE, int $fore_color = QR_BLACK,) : void`

Fix Code:

`public static function svg (string $text, $outfile = false, $level = QR_ECLEVEL_L, int $size = 3, int $margin = 4, bool $saveAndPrint = false, int $back_color = QR_WHITE, int $fore_color = QR_BLACK) : void`

Thanks

**Comment by giauphan** [comment]
@Daniele1985  
Thank you for catching that issue! The extra comma at the end of the parameter list in the svg method declaration on line 234 of ``QR_CODE.php`` is only compatible with PHP 8.0 and above, where trailing commas in function arguments are allowed.

If you're using PHP 7.x or lower, this comma will cause a syntax error.

Original Code:
```php
public static function svg (string $text, $outfile = false, $level = QR_ECLEVEL_L, int $size = 3, int $margin = 4, bool $saveAndPrint = false, int $back_color = QR_WHITE, int $fore_color = QR_BLACK,) : void
```
Fixed Code:

```php
public static function svg (string $text, $outfile = false, $level = QR_ECLEVEL_L, int $size = 3, int $margin = 4, bool $saveAndPrint = false, int $back_color = QR_WHITE, int $fore_color = QR_BLACK) : void
```
I've removed the extra comma in the source code. Thanks for catching that!
